const verifyToken = require('../../middleware/verifyToken');
const add = require('./add');
const addTestTimeTable = require('./addTestTimeTable');
const completeTest = require('./completeTest');
const getTestSubjects = require('./getTestSubjects');
const listExam = require('./listExam');
const listExamSection = require('./listExamSection');
const listSection = require('./listSection');
const listTerm = require('./listTerm');
const listTermSection = require('./listTermSection');
const listTest = require('./listTest');
const listTestSection = require('./listTestSection');
const patternSubjectValidate = require('./patternSubjectValidate');
const sectionTestValidate = require('./sectionTestValidate');
const updateScheduleExam = require('./updateScheduleExam');
const updateScheduleSection = require('./updateScheduleSection');
const updateScheduleTerm = require('./updateScheduleTerm');
const updateScheduleTest = require('./updateScheduleTest');
const updateTestTimeTable = require('./updateTestTimeTable');

module.exports = (server) => {
    server.post('/v1/test/schedule', verifyToken, add);
    server.post('/v1/test/timetable', verifyToken, addTestTimeTable);
    server.put('/v1/test/complete', verifyToken, completeTest);
    server.get('/v1/schedule/test/subjects', verifyToken, getTestSubjects);
    server.get('/v1/schedule/list/exam', verifyToken, listExam);
    server.get('/v1/schedule/list/section/exam', verifyToken, listExamSection);
    server.get('/v1/schedule/list/section', verifyToken, listSection);
    server.get('/v1/schedule/list/term', verifyToken, listTerm);
    server.get('/v1/schedule/list/section/term', verifyToken, listTermSection);
    server.get('/v1/schedule/list/test', verifyToken, listTest);
    server.get('/v1/schedule/list/section/test', verifyToken, listTestSection);
    server.get('/v1/pattern/subject/validate', verifyToken, patternSubjectValidate);
    server.get('/v1/schedule/test/validate', verifyToken, sectionTestValidate);
    server.put('/v1/exam/schedule', verifyToken, updateScheduleExam);
    server.put('/v1/section/schedule', verifyToken, updateScheduleSection);
    server.put('/v1/term/schedule', verifyToken, updateScheduleTerm);
    server.put('/v1/test/schedule', verifyToken, updateScheduleTest);
    server.put('/v1/test/timetable', verifyToken, updateTestTimeTable);
};
